# PostgreSQL configuration
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: adminmr # Updated username
  password: <%= ENV['DATABASE_PASSWORD'] %> # Use environment variable for security
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %> # Defaults to localhost if not set
  port: <%= ENV.fetch('DATABASE_PORT', 5432) %> # Defaults to 5432 if not set

development:
  <<: *default
  database: belle_artistry_db_development

test:
  <<: *default
  database: belle_artistry_db_test

production:
  <<: *default
  database: belle_artistry_db_production
  # Note: Keeping the username 'adminmr' consistent across environments for simplicity,
  # but in a real-world scenario, it's common to have different users for different environments
  # for better security practices. Adjust accordingly based on your deployment needs.
